### PR TITLE
Allow '+' in Jinja variable whitespace rules

### LINKED ISSUE #17: Fix whitespace control in Jinja rules
Currently only the `-` character is accepted by the Jinja whitespace rules but technically `+` should be supported as well, i.e.:

    {%+ ... +%}
    {{+ ... +}}
    {#+ ... +#}

That's mentioned in the [upstream documentation](https://jinja.palletsprojects.com/en/2.10.x/templates/#whitespace-control) as well.

Thanks @myii, for mentioning this is 
https://github.com/roaldnefs/salt-lint/pull/13#issuecomment-538547711!

### PR DESCRIPTION
**Pull request by FLeXyo**
Fixes #17

### CODE REVIEW

**Comment by myii** [comment]
@FLeXyo I'm not the maintainer here but a little feedback but great job.  The tests would have to be updated as well, though:

https://github.com/roaldnefs/salt-lint/blob/025a8e7dc451ed76f34cdb25a73146ab6efe1be1/tests/unit/TestJinjaCommentHasSpaces.py#L12-L18

https://github.com/roaldnefs/salt-lint/blob/025a8e7dc451ed76f34cdb25a73146ab6efe1be1/tests/unit/TestJinjaStatementHasSpaces.py#L12-L18

https://github.com/roaldnefs/salt-lint/blob/025a8e7dc451ed76f34cdb25a73146ab6efe1be1/tests/unit/TestJinjaVariableHasSpaces.py#L12-L18

How about leaving the opening one as a `-` and the closing one as a `+`?

**Comment by FLeXyo** [comment]
@myii Thanks a lot for your feedback! I've updated the tests :)

**Comment by myii** [comment]
@FLeXyo You're welcome, this got fixed much faster than I expected!

**Comment by kyentei** [comment]
Looks good! Thanks for your contributions! :-)

**Pull request merged**
